# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-17 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
